// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int testNum = Integer.parseInt(args[0]);
		double small = 0;
		double big = 0;
		double ratio;
		double random;
		for (int i = 0; i <testNum; i++) {
			random = Math.random();
			if (random > 0.5) {
				big++;
			}
			else {
				small++;
			}
		}
		if (small > big){
			if (big == 0){
				ratio = 0;
			}
			else {
				ratio = big/small;	
			}
		}
		else {
			if (small == 0){
				ratio = 0;
			}
			else {
				ratio = small/big;	
			}
		}
		int smallInt = (int) small;
		int bigInt = (int) big;
		System.out.println("> 0.5:   " + bigInt + " times");
		System.out.println("<= 0.5:  " + smallInt + " times");
		if (ratio != 0) {
			System.out.println("Ratio:   " + ratio);
		}
	}
}
